### PR TITLE
ID + minor fix

### PR DESCRIPTION
**Pull request by nrafal**
Added IDs in rows for better logstash + elastic handling, also fixed "Ł" as age in  since it is probably mistake and brakes automatic migration as it can be treated as number.

### CODE REVIEW

**Comment by nrafal** [comment]
@dtandev is there a reason you don't want to provide an ID for each row?

**Comment by dtandev** [comment]
> Added IDs in rows for better logstash + elastic handling, also fixed "Ł" as age in since it is probably mistake and brakes automatic migration as it can be treated as number.

Sorry for 'Ł'. FIxed.

**Comment by dtandev** [comment]
> @dtandev is there a reason you don't want to provide an ID for each row?

1. We don't need it for our purposes. Pandas do it for us. 
2. In CSV file, new rows are added below existing rows with data for specific provinces. That helps control the number of all cases in provinces. Adding ID's is extra and not necessary work. And they will change after every update.

**Comment by nrafal** [comment]
That makes some sense, but makes it harder to process, since I have to
throw out data and reindex it with each update. If you'd updated it with
newest records down the file it would be easier - just automatically
following changes and indexing new rows.

Still thanks for doing great work with that dataset!

śr., 1 kwi 2020, 22:15 użytkownik Dariusz Tanajewski <
notifications@github.com> napisał:

**Pull request closed without merging**
